version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: unless-stopped
    ports:
      - '5556:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=uniquesecret
      - POSTGRES_DB=todos
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local